title: A Ultra Light Robotics Magazine
description: > # this means to ignore newlines until "baseurl:"
  ROBOTICronics is your fashionable news website. We provide you
  with the latest breaking news straight from th industry technology.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://roboticronics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: 3agv2004 #if your site has a twitter account, enter it here

# Author Settings
author: 3agv2004 # add your name
author-img: io.jpg # add your photo
about-author: I am a Instructional Junior Designer. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: 3agv2004 # add your Github handle
social-linkedin: voglinogiuseppe# add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-3agv2004 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
